services:
  picpaychallenge.api:
    image: picpaychallenge.api
    build:
      context: .
      dockerfile: PicPayChallenge.Api/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PicPayDb;User Id=sa;Password=Your_password123;
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver
    ports: 
      - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    volumes: 
      - ./init-scripts:/docker-entrypoint-initdb.d
